export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_BY_HANDLE = 'GET_PROFILE_BY_HANDLE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
